### ISSUE TITLE
Wazuh packages redesign tier 1 - Use secret for AWS region

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#170]
## Description

Due to the https://github.com/wazuh/wazuh-jenkins/issues/6425 issue, it is needed for all repositories involved in the Packages redesign objective to add an authentication step to AWS, so the workflows do not use a hardcoded region

The secret name is: `CI_AWS_REGION`

```
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: ${{ secrets.CI_AWS_REGION }}
```
