### ISSUE TITLE
Wazuh Dashboard Ingress - 401 unauthorised

### ISSUE THREAD

**Issue by Sam-Sundar** [wazuh/wazuh-dashboard#31]
**Describe the bug**
Hey Team,

We've installed Wazuh on a Kubernetes cluster and have attached a domain for it. Wazuh was working without any issues.

We then introduced ingress and our idea was to have path based routing for Wazuh under a common domain. 

We also changed the dashboard values like below and after implementing when we hit the server with `/wazuh` path, we are getting `401 un-authorised` error. 

Below are the logs, 
```json
{
    "type": "response",
    "@timestamp": "2023-03-02T14:40:47Z",
    "tags": [],
    "pid": 40,
    "method": "get",
    "statusCode": 401,
    "req": {
        "url": "/wazuh/app/wazuh/app/wazuh",
        "method": "get",
        "headers": {
            "host": "devops.justcall.dev",
            "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Brave\";v=\"109\", \"Chromium\";v=\"109\"",
            "sec-ch-ua-mobile": "?0",
            "sec-ch-ua-platform": "\"macOS\"",
            "upgrade-insecure-requests": "1",
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
            "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
            "sec-gpc": "1",
            "accept-language": "en-GB,en;q=0.5",
            "sec-fetch-site": "none",
            "sec-fetch-mode": "navigate",
            "sec-fetch-user": "?1",
            "sec-fetch-dest": "document",
            "accept-encoding": "gzip, deflate, br",
            "x-cloud-trace-context": "ed365d0a4d5357728a1ee65f9bc91aa2/688693293495436800",
            "via": "1.1 google",
            "x-forwarded-for": "34.170.144.15, 34.120.67.126,35.191.17.219",
            "x-forwarded-proto": "http",
            "x-envoy-external-address": "35.191.17.219",
            "x-request-id": "029a7d75-56e8-46c0-b78f-5d1e4a54f479",
            "x-envoy-decorator-operation": "dashboard.wazuh.svc.cluster.local:80/wazuh*",
            "x-envoy-peer-metadata": "",
            "x-envoy-peer-metadata-id": "router~10.68.9.10~istio-ingressgateway-5d4f4fcfb7-mzcdc.istio-ingress~istio-ingress.svc.cluster.local",
            "x-envoy-attempt-count": "1",
            "x-envoy-original-path": "/wazuh/app/wazuh",
            "x-b3-traceid": "780c9c1ded01d42f4dcd8ec7c88ba47d",
            "x-b3-spanid": "4dcd8ec7c88ba47d",
            "x-b3-sampled": "0"
        },
        "remoteAddress": "10.68.9.10",
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
    },
    "res": {
        "statusCode": 401,
        "responseTime": 2,
        "contentLength": 9
    },
    "message": "GET /wazuh/app/wazuh 401 2ms - 9.0B"
}
```

Below is the dashboard values yaml. 

```yaml
opensearch_dashboards.yml: |2-

    server.host: 0.0.0.0
    server.port: 5601
    opensearch.hosts: https://indexer:9200
    opensearch.ssl.verificationMode: none
    opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
    opensearch_security.multitenancy.enabled: false
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]
    server.ssl.enabled: false
    server.ssl.key: "/usr/share/wazuh-dashboard/config/certs/key.pem"
    server.ssl.certificate: "/usr/share/wazuh-dashboard/config/certs/cert.pem"
    opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/config/certs/root-ca.pem"]
    uiSettings.overrides.defaultRoute: /wazuh/app/wazuh
```
