### ISSUE TITLE
Reduce default session cookie timeout

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#739]
# Description

Currently, the Wazuh Dashboard Security plugin expires the logged-in user session cookie after 1 hour by default. We need to reduce the default session and cookie TTL to 15 minutes (900000 ms).

In addition, the `wazuh-security-plugin` must be updated so that if the following settings are not explicitly defined in the `opensearch_dashboard.yml` file, the session and cookie timeouts default to 15 minutes.
This allows existing installations to benefit from the new security defaults without requiring manual configuration in the deployment files.

Related code:
https://github.com/opensearch-project/security-dashboards-plugin/blob/2.19.2.0/server/auth/types/basic/basic_auth.ts#L86

Related settings:

```yaml
opensearch_security.cookie.ttl: 86400000
opensearch_security.session.ttl: 86400000
opensearch_security.session.keepalive: true
```

## Tasks

- [x] Reduce default session cookie timeout to 15 minutes
- [x] Update wazuh-security-plugin to apply 15-minute defaults when no explicit config is provided
