### ISSUE TITLE
Loading bar present using custom branding

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#86]
## Description

Using a custom loading logo enables the loading bar in the UI, which is not present using the default branding. I think this is a great feature and should be enabled in the default mode too.
I'm aware that an animated loading logo was included in #77, so this feature request might be simply ignored. I'm only creating the issue, so you are aware of this.

```yml
opensearchDashboards.branding:
  loadingLogo:
    defaultUrl: "https://logowik.com/content/uploads/images/f1-formula-18381.jpg"
```

![image](https://github.com/wazuh/wazuh-dashboard/assets/15186973/97d2718e-89ab-43a1-a452-8becf2120ba1)
